### ISSUE TITLE
Submit session proposal

### ISSUE THREAD

**Issue by joeroe** [sslarch/caa2021_packages#1]
Thanks again for volunteering to help with this @MartinHinz and @nevrome! I've just pushed a first draft of the abstract. The deadline for submission is **Sunday 15 November**.

Please feel free to edit directly or submit a pull request with suggestions. The limit for the abstract is 1000 words plus references, which seems a bit crazy to me; I'd prefer to keep it to less than a page. More guidance at https://2021.caaconference.org/call-for-sessions/.

May also be of interest to @benmarwick, @SCSchmidt, and @cshoggard, who were kind enough to offer suggestions on the mailing list. And I hope Sophie and Ben don't mind me poaching their phrasing to frame the session :)

**Comment by joeroe** [comment]
While I was writing the draft I also rediscovered [this discussion](/zackbatist/open-archaeo/issues/1) which has many relevant ideas for the session.

In particular, I remembered @benmarwick's suggestion of looking at if any [TFQA](http://tfqa.com/index.html) programs could be ported to R. That could be a good prompt for a what-should-we-do-next discussion (at CAA or elsewhere), so I've started trying to list what TFQA functionality is currently available in R at [sslarch/tfqar](/sslarch/tfqar) (putting it under the SIG organisation seemed most appropriate, hope that's okay!)

**Comment by MartinHinz** [comment]
Perfect, I like this very much. Am I right to assume that we are good to go?

**Comment by joeroe** [comment]
We are for me. Since the deadline isn't looming, we can leave it open for further suggestions for a few days. But I would like to submit it by Friday latest.

**Comment by MartinHinz** [comment]
Ok for me. I set me an alarm... ;-)

**Comment by nevrome** [comment]
I'm also very happy with the abstract :+1: - Thanks for bringing this together so quickly

**Comment by joeroe** [comment]
Submitted, thanks all!

**Comment by MartinHinz** [comment]
Thank you so much!
--
Universität Bern
Institut für Archäologische Wissenschaften
Prähistorische Archäologie (Ur- und Frühgeschichte)
und Oeschger Centre for Climate Change Research (OCCR)

Dr. Martin Hinz

Mittelstrasse 43, 3012 Bern
martin.hinz@iaw.unibe.ch
Tel. +41 31 631 5826
iaw.unibe.ch | oeschger.unibe.ch
